spring:
  application:
    name: skhu-connect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${PORT:8080}

app:
  mail:
    from: ${MAIL_FROM}
  jwt:
    secret: ${JWT_SECRET}
    cookie-secure: ${JWT_COOKIE_SECURE:false}
