package org.skhuconnect.admin.notificationlog.entity;
public enum NotificationLogType { THRESHOLD_REACHED, ANSWER_REGISTERED, ANSWER_UPDATED, PETITION_HIDDEN, PETITION_RESTORED, COMMENT_HIDDEN, COMMENT_RESTORED, THRESHOLD_SETTING_UPDATED, NOTICE_PUBLISHED }
